### PR TITLE
Added file on France

### PR DESCRIPTION
**Pull request by djhoese**
Adds population and capitol for France.

### CODE REVIEW

**Comment by sstevens2** [comment]
Hi Dave, Great PR!  We've updated our standard requirements and we need you to add the largest city as well.

**Comment by djhoese** [comment]
Will do.

**Comment by djhoese** [comment]
@sstevens2 I think I fixed everything. This is ready for review now.

**Comment by sstevens2** [comment]
That looks great!  I'll merge it. 😄

**Pull request merged**
